language: python
dist: xenial
sudo: true
python:
  - "3.8"
install:
  - pip install tox
  - pip install tox-travis
script:
  - tox
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libssl-dev swig
